# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cvSearchDesign_v4.ui',
# licensing of 'cvSearchDesign_v4.ui' applies.
#
# Created: Tue Sep  3 18:22:30 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 823)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(81, 197, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(81, 197, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pBAjoutCV = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBAjoutCV.sizePolicy().hasHeightForWidth())
        self.pBAjoutCV.setSizePolicy(sizePolicy)
        self.pBAjoutCV.setMinimumSize(QtCore.QSize(180, 0))
        self.pBAjoutCV.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pBAjoutCV.setFont(font)
        self.pBAjoutCV.setCursor(QtCore.Qt.PointingHandCursor)
        self.pBAjoutCV.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:0.894472 rgba(0, 170, 255, 255));")
        self.pBAjoutCV.setObjectName("pBAjoutCV")
        self.horizontalLayout_5.addWidget(self.pBAjoutCV)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lEKeyWord = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lEKeyWord.sizePolicy().hasHeightForWidth())
        self.lEKeyWord.setSizePolicy(sizePolicy)
        self.lEKeyWord.setMinimumSize(QtCore.QSize(200, 0))
        self.lEKeyWord.setText("")
        self.lEKeyWord.setObjectName("lEKeyWord")
        self.horizontalLayout.addWidget(self.lEKeyWord)
        self.pBAddKeyWord = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBAddKeyWord.sizePolicy().hasHeightForWidth())
        self.pBAddKeyWord.setSizePolicy(sizePolicy)
        self.pBAddKeyWord.setMinimumSize(QtCore.QSize(100, 0))
        self.pBAddKeyWord.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pBAddKeyWord.setFont(font)
        self.pBAddKeyWord.setCursor(QtCore.Qt.PointingHandCursor)
        self.pBAddKeyWord.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:0.894472 rgba(0, 170, 255, 255));")
        self.pBAddKeyWord.setObjectName("pBAddKeyWord")
        self.horizontalLayout.addWidget(self.pBAddKeyWord)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tWKeyWord = QtWidgets.QTableWidget(self.centralwidget)
        self.tWKeyWord.setObjectName("tWKeyWord")
        self.tWKeyWord.setColumnCount(0)
        self.tWKeyWord.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tWKeyWord)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.pBResearch = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBResearch.sizePolicy().hasHeightForWidth())
        self.pBResearch.setSizePolicy(sizePolicy)
        self.pBResearch.setMinimumSize(QtCore.QSize(180, 0))
        self.pBResearch.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pBResearch.setFont(font)
        self.pBResearch.setCursor(QtCore.Qt.PointingHandCursor)
        self.pBResearch.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:0.894472 rgba(0, 170, 255, 255));")
        self.pBResearch.setObjectName("pBResearch")
        self.verticalLayout_3.addWidget(self.pBResearch)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pBClearKW = QtWidgets.QPushButton(self.centralwidget)
        self.pBClearKW.setMinimumSize(QtCore.QSize(180, 0))
        self.pBClearKW.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pBClearKW.setFont(font)
        self.pBClearKW.setCursor(QtCore.Qt.PointingHandCursor)
        self.pBClearKW.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:0.894472 rgba(0, 170, 255, 255));")
        self.pBClearKW.setObjectName("pBClearKW")
        self.horizontalLayout_6.addWidget(self.pBClearKW)
        spacerItem6 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.tWResults = QtWidgets.QTableWidget(self.centralwidget)
        self.tWResults.setMinimumSize(QtCore.QSize(400, 0))
        self.tWResults.setObjectName("tWResults")
        self.tWResults.setColumnCount(0)
        self.tWResults.setRowCount(0)
        self.verticalLayout.addWidget(self.tWResults)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pBNewRequest = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBNewRequest.sizePolicy().hasHeightForWidth())
        self.pBNewRequest.setSizePolicy(sizePolicy)
        self.pBNewRequest.setMinimumSize(QtCore.QSize(150, 0))
        self.pBNewRequest.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pBNewRequest.setFont(font)
        self.pBNewRequest.setCursor(QtCore.Qt.PointingHandCursor)
        self.pBNewRequest.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:0.894472 rgba(0, 170, 255, 255));")
        self.pBNewRequest.setObjectName("pBNewRequest")
        self.horizontalLayout_4.addWidget(self.pBNewRequest)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "CVSearch", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "And Find!", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir CVs (pdf, docx, pptx ou txt) :", None, -1))
        self.pBAjoutCV.setText(QtWidgets.QApplication.translate("MainWindow", "Importer CVs", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Keyword à rechercher :", None, -1))
        self.pBAddKeyWord.setText(QtWidgets.QApplication.translate("MainWindow", "Ajout Keyword", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Lancer Recherche :", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "(pas trop fort, ça peut faire mal)", None, -1))
        self.pBResearch.setText(QtWidgets.QApplication.translate("MainWindow", "Rechercher CVs", None, -1))
        self.pBClearKW.setText(QtWidgets.QApplication.translate("MainWindow", "Clear KeyWords", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Et les gagnants sont.....", None, -1))
        self.pBNewRequest.setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle Recherche", None, -1))

